title: Yannick's Blog
email: yannick.eisenschmidt@gmail.com
description: Das ist mein Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.eisenschmidt.dev"
twitter_username: jekyllrb
github_username:  eisenschmidt

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .github
  - .gitignore
  - .git
  - Dockerfile
  - local_build.sh